version: '3'

services:
  webserver:
    image: 'nginx:1.15.3-alpine'
    container_name: webserver-api-platform
    restart: on-failure
    ports:
      - '8000:80'
    volumes:
      - ./public:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    container_name: php-api-platform
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - db
  db:
    container_name: db-api-platform
    image: mariadb:10.4.7
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080