version: '3'

services:
  nginx:
    image: 'nginx:1.15.3-alpine'
    container_name: nginx-app
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./public:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    links:
      - mariadb
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    container_name: mysqlASW
    image: mariadb:10.4.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}